Feature/implement identity microservice
denis-pptx/PreownedMarket pull request #2
Opened 2024-03-29 07:16 UTC by denis-pptx

2024-03-29 09:50 UTC, denis-pptx commented
Points to be corrected:
1) Use Global exception handler instead of a lot
2) Add FromQuery / FromBody / ... to Actions in Controllers 
3) Add tokens expiry time to appsettings.json
4) Manual mapping or specifying properties for mapping
5) Add messages to custom exceptions
6) [optional] logging with pipeline behaviour

2024-04-12 07:31 UTC, Elizaveta564 requested changes

2024-04-12 07:31 UTC, Elizaveta564 commented on src/Services/Identity/Identity.Application/Features/Identity/Commands/LoginUser/LoginUserVm.cs
> +public record LoginUserVm(string AccessToken, string RefreshToken);
let's make this entity a dto object and move it to the dtos folder

2024-04-12 07:31 UTC, Elizaveta564 commented on src/Services/Identity/Identity.Application/Features/Identity/Commands/LoginUser/LoginUserCommand.cs
> +    : ICommand<LoginUserVm>;
the dto must be passed to the command

2024-04-12 07:31 UTC, Elizaveta564 commented on src/Services/Identity/Identity.Application/Features/Identity/Commands/LoginUser/LoginUserHandler.cs
> +        if (user is null)
there should be an empty line here

2024-04-12 07:31 UTC, Elizaveta564 commented on src/Services/Identity/Identity.Application/Features/Identity/Commands/LoginUser/LoginUserHandler.cs
> +            throw new UnauthorizedException("Incorrect Email or Password");
move constants to a separate file

2024-04-12 07:31 UTC, Elizaveta564 commented on src/Services/Identity/Identity.Application/Features/Identity/Commands/LoginUser/LoginUserHandler.cs
> +        if (!isPasswordValid)
there should be an empty line here

2024-04-12 07:31 UTC, Elizaveta564 commented on src/Services/Identity/Identity.Application/Features/Identity/Commands/LoginUser/LoginUserHandler.cs
> +        await _userManager.UpdateAsync(user);
there should be an empty line here

2024-04-12 07:31 UTC, Elizaveta564 commented on src/Services/Identity/Identity.Application/Features/Identity/Commands/RefreshToken/RefreshTokenVm.cs
> +public record RefreshTokenVm(string AccessToken, string RefreshToken);
create dto

2024-04-12 07:31 UTC, Elizaveta564 commented on src/Services/Identity/Identity.Application/Features/Identity/Commands/RefreshToken/RefreshTokenCommand.cs
> +    : ICommand<RefreshTokenVm>;
pass dto

2024-04-12 07:31 UTC, Elizaveta564 commented on src/Services/Identity/Identity.Application/Features/Identity/Commands/RefreshToken/RefreshTokenHandler.cs
> +        if (userId is null)
there should be an empty line here

2024-04-12 07:31 UTC, Elizaveta564 commented on src/Services/Identity/Identity.Application/Features/Identity/Commands/RefreshToken/RefreshTokenHandler.cs
> +        if (user is null ||
tha same

2024-04-12 07:31 UTC, Elizaveta564 commented on src/Services/Identity/Identity.Application/Features/Identity/Commands/RegisterUser/RegisterUserCommand.cs
> +    : ICommand<Unit>;
pass dto

2024-04-12 07:31 UTC, Elizaveta564 commented on src/Services/Identity/Identity.Application/Features/Users/Commands/DeleteUser/DeleteUserByIdHandler.cs
> +        if (userIdentity == null)
there should be an empty line here

2024-04-12 07:31 UTC, Elizaveta564 commented on src/Services/Identity/Identity.Application/Features/Users/Commands/UpdateUserRole/UpdateUserRoleHandler.cs
> +        string? newRole = (await _roleManager.FindByNameAsync(request.NewRole))?.Name;
use 'var'

2024-04-12 07:31 UTC, Elizaveta564 commented on src/Services/Identity/Identity.Application/Features/Users/Queries/GetAllUsers/GetAllUsersHandler.cs
> +            userVm.Role = role ?? string.Empty;
why might a user not have a role?

2024-04-12 07:31 UTC, Elizaveta564 commented on src/Services/Identity/Identity.Application/Features/Users/Queries/Models/UserVm.cs
> +}
create dto

2024-04-12 07:31 UTC, Elizaveta564 commented on src/Services/Identity/Identity.Infrastructure/Authentication/JwtProvider.cs
> +    IOptions<JwtOptions> _jwtOptions,
move it to Application

2024-04-12 07:31 UTC, Elizaveta564 commented on src/Services/Identity/Identity.Infrastructure/Authentication/JwtOptions.cs
> +{
move it to Application

2024-04-12 07:31 UTC, Elizaveta564 commented on src/Services/Identity/Identity.Infrastructure/Data/ApplicationDbContext.cs
> +    }
use migration

2024-04-12 07:31 UTC, Elizaveta564 commented on src/Services/Identity/Identity.WebUI/Controllers/AuthController.cs
> +    {
dto must be passed as an input parameter

2024-04-12 07:31 UTC, Elizaveta564 commented on src/Services/Identity/Identity.WebUI/Program.cs
extra lines

2024-04-12 07:31 UTC, Elizaveta564 commented on src/Services/Identity/Identity.WebUI/Program.cs
> +//    options => options.UseMySql(connection, new MySqlServerVersion(new Version(8, 3, 0))));
delete comments

2024-04-12 07:31 UTC, Elizaveta564 commented on src/Services/Identity/Identity.WebUI/Program.cs
> +
extra line

2024-04-22 10:16 UTC, mebry approved these changes

2024-04-22 10:16 UTC, mebry commented on src/Services/Identity/Identity.Application/Features/Users/Commands/DeleteUser/DeleteUserByIdHandler.cs
> +        if (userIdentity == null)
is null

2024-04-22 10:16 UTC, mebry commented on src/Services/Identity/Identity.Application/Features/Users/Queries/GetUserById/GetUserByIdHandler.cs
> +        string? role = (await _userManager.GetRolesAsync(user)).Single();
use var

2024-04-22 12:34 UTC, merged