Feature/implement item microservice
denis-pptx/PreownedMarket pull request #4
Opened 2024-04-10 11:00 UTC by denis-pptx

2024-04-12 07:46 UTC, Elizaveta564 requested changes

2024-04-12 07:46 UTC, Elizaveta564 commented on src/Services/Item/Item.DataAccess/Data/ApplicationDbContext.cs
> +    }
use migration

2024-04-12 07:46 UTC, Elizaveta564 commented on src/Services/Item/Item.BusinessLogic/Services/Implementations/ItemImageService.cs
> +            throw new NotFoundException(GenericErrorMessages<Item>.NotFound);
use 'if'

2024-04-12 07:46 UTC, Elizaveta564 commented on src/Services/Item/Item.BusinessLogic/Services/Implementations/ItemImageService.cs
> +            throw new NotFoundException(GenericErrorMessages<Item>.NotFound);
the same

2024-04-12 07:46 UTC, Elizaveta564 commented on src/Services/Item/Item.Presentation/Program.cs
> +//    options => options.UseSqlite(connection));
delete comments

2024-04-12 07:46 UTC, Elizaveta564 commented on src/Services/Item/Item.Presentation/Program.cs
> +
extra line

2024-04-22 10:13 UTC, mebry requested changes

2024-04-22 10:13 UTC, mebry commented on src/Services/Item/Item.BusinessLogic/Models/Common/PagedList.cs
> +    }
When describing a class, use the following structure:
· Declare all class members, including readonly or constants
· Declare all public properties, including auto-properties
· Declare all constructor(s)
· Declare the destructor, if any
· Declare all public methods
· Declare all protected methods
· Declare all private methods

2024-04-22 10:13 UTC, mebry commented on src/Services/Item/Item.BusinessLogic/Models/Validators/CategoryValidator.cs
> +        RuleFor(c => c.Name)
Let's use more descriptive names to make it clear. "с"

2024-04-22 10:13 UTC, mebry commented on src/Services/Item/Item.BusinessLogic/Models/Validators/ItemValidator.cs
> +        RuleFor(x => x.Description)
the same

2024-04-22 10:13 UTC, mebry commented on src/Services/Item/Item.BusinessLogic/Services/Implementations/BaseService.cs
> +public abstract class BaseService<TEntity, TEntityDto> : IBaseService<TEntity, TEntityDto>
For the future, keep in mind that they do not make a basic service for services

2024-04-22 10:13 UTC, mebry commented on src/Services/Item/Item.BusinessLogic/Services/Implementations/ItemService.cs
> +        }
there is a heavy load on the services here, it is better to take it out in the repository. Since returning IQueryable to services is a bad idea

2024-04-22 10:13 UTC, mebry commented on src/Services/Item/Item.DataAccess/Data/Configurations/CategoryConfiguration.cs
> +        builder.HasIndex(x => x.Name).IsUnique();
Let's use more descriptive names to make it clear

2024-04-22 19:10 UTC, mebry approved these changes

2024-04-22 20:08 UTC, merged